# Generated by Django 5.2.4 on 2025-08-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkDesk', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(default='TEMP1', max_length=100),
        ),
        migrations.AddField(
            model_name='technicians',
            name='role',
            field=models.CharField(default='TEMP1', max_length=100),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
