# Generated by Django 5.2.4 on 2025-08-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkDesk', '0003_admin_role_technicians_role_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='technicians',
            name='role',
            field=models.CharField(default='technician', max_length=100),
        ),
    ]
