# Generated by Django 5.2.4 on 2025-08-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkDesk', '0004_alter_admin_role_alter_technicians_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=10000)),
                ('technician_id', models.IntegerField()),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
            ],
        ),
    ]
