# Generated by Django 5.2.4 on 2025-08-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkDesk', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Not started', max_length=100),
        ),
    ]
