# Generated by Django 5.2.4 on 2025-08-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkDesk', '0006_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='technician_id',
        ),
        migrations.AddField(
            model_name='task',
            name='technician_name',
            field=models.CharField(default='Nobody'),
        ),
    ]
