# Generated by Django 5.2.4 on 2025-08-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkDesk', '0007_remove_task_technician_id_task_technician_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicians',
            name='status',
            field=models.CharField(default='available'),
        ),
    ]
