# Generated by Django 5.2.4 on 2025-08-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkDesk', '0008_technicians_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicians',
            name='contact',
            field=models.CharField(default='123-456-7890'),
        ),
    ]
