# Generated by Django 5.2.4 on 2025-08-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkDesk', '0009_technicians_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='Low', max_length=100),
        ),
    ]
