# Generated by Django 5.2.4 on 2025-08-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkDesk', '0010_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
