# Generated by Django 5.2.4 on 2025-08-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkDesk', '0013_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
