# Generated by Django 5.2.4 on 2025-08-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkDesk', '0014_alter_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_by',
        ),
    ]
