# Generated by Django 5.2.4 on 2025-09-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkDesk', '0016_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unavailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_id', models.CharField()),
                ('reason', models.CharField(max_length=1000)),
            ],
        ),
    ]
